version: '3.4'

services:
  gateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  pet.file.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  pet.identity.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  pet.reservation.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  pet.user.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

